### ISSUE TITLE
Volume issue with reels

### ISSUE THREAD

**Issue by infini667** [Arcus92/instagram-video-control#1]
Hey, man! Your extension is very good! Thanks for this. It's simple, adds video controls and saves the volume between videos. Just a little thing: it's not keeping the volume enabled when watching reels (I have to enable the volume/unmute manually for every video). Edit: there's also an issue with accessing the controls/volume seeing stories (can't access because of the Instagram reply field).

**Comment by Arcus92** [comment]
Hi @infini667 ,
Thanks for reporting the issue. To be honest, I don't use Reels at all. Instagram added some changes that broke the plugin and I missed that.
However, this should be fixed in 0.4. It is currently in review by Google and Mozilla and should be released later today.
