### ISSUE TITLE
Double bug: return of instagram normal controls + button detection zone too small

### ISSUE THREAD

**Issue by Felina-Lain** [Arcus92/instagram-video-control#17]
Hi, first: thanks for the amazing extension, I literally cannot go without anymore.
But I came across two bugs those days (might be that instagram changed a few things on their side?)
First the instagram default controls (which before were hidden by your extension) are now visible again:
![image](https://github.com/Arcus92/instagram-video-control/assets/5339303/f89f9029-aed1-4bb0-9dd6-6299f388842e)
You can see the double mute button on the bottom right.

Second bug: the detection zone for the button is either slightly out of alignement, or too small. For exemple when I try to use the bar for the sound, I have to click below the bar, because if I try to move to hover on it, the controls disappear:
![insta buttons](https://github.com/Arcus92/instagram-video-control/assets/5339303/2168953f-7290-4f44-99b5-a82496382bb2)
This specific bug started about 4-5 days ago (or at least I noticed it at that time). Before that I could click the buttons right on top of them and it would work.

Thanks again for the app in any cases (because even with those bugs, I can't even think of not using it XD)

**Comment by Arcus92** [comment]
Hi,
I tired to re-add the default Instagram controls in the last update. There were complains about the missing share/like buttons, hashtags, playing song, etc. in Stories and Reels. I just moved the controls up a bit, but apparently not far enough for Chrome users. This causing the issues with the clickable area in the volume controls.

I'm working on a custom, slim player-bar that will look identical in Firefox and Chrome and fixes some issues with the browsers default behavior. But it will take a few more days.
![grafik](https://github.com/Arcus92/instagram-video-control/assets/6116717/04db07bf-23d7-48df-ba03-c26c81a9e6f7)

**Comment by Arcus92** [comment]
Hi @Felina-Lain,
The v1.0.1 update is finally available in the Chrome Web Store and you should have received the new player bar. 
Please let me know if everything is working for you.

**Comment by Felina-Lain** [comment]
> Hi @Felina-Lain, The v1.0.1 update is finally available in the Chrome Web Store and you should have received the new player bar. Please let me know if everything is working for you.

Heya!
Yeah I saw it today, it's working super well!
