### ISSUE TITLE
Feature request: an option to always unmute Instagram by default

### ISSUE THREAD

**Issue by dspjm** [Arcus92/instagram-video-control#37]
I am on Firefox and when I open Instagram page every time or enter profile pages, the videos are always muted by default. I have to click the unmute button in the video control.

Would be nice if this add-on allows an option to always unmute the videos by default.

Thanks.

**Comment by Arcus92** [comment]
Hi, I was going to implement this and restore the previous mute state.
However, this is a limitation of modern browser. You can not have auto-unmute and auto-play. Unless the user explicitly clicks in the website, the extension is not allowed to change the mute state.

I can add a toggle to enable auto-unmute in the settings. This would pause all videos on the initial page load until the user clicks the play button again. Unless the user manually change this option in the website settings:
![image](https://github.com/Arcus92/instagram-video-control/assets/6116717/3edc383f-e477-44d2-9529-780c51de4aae)
I'll try to add a hint/info in the settings menu, when this option is enabled then.

**Comment by Arcus92** [comment]
New options looks like this:
![image](https://github.com/Arcus92/instagram-video-control/assets/6116717/3040a8fa-2e05-4e6a-9334-11381b3ed4f6)

Is this understandable? I might add browser specific descriptions.

**Comment by dspjm** [comment]
> Is this understandable? I might add browser specific descriptions.

Thanks. I think it's understandable. It means to allow autoplay and the videos will be unmuted automatically.
