### ISSUE TITLE
Invisible icon in dark mode

### ISSUE THREAD

**Issue by juarez-spa3** [Arcus92/instagram-video-control#8]
It's not a big problem, but I wanted to report it anyway. The extension icon is not visible if the browser is in dark mode.

![resim](https://github.com/Arcus92/instagram-video-control/assets/153795294/afce04cc-0948-4154-a4d4-9da0c82aa462)

**Comment by Arcus92** [comment]
Good point. Thanks for reporting. 
Since the app icon serves no purpose, you can simply hide it in the plugin menu.

Manifest v3 supports multiple icons for light and dark theme. I should be able to fix this by adding a dark-theme icon or simply add a white outline.
